media:
  - name: documents
    label: Documents
    input: files/documents
    output: /files/documents
    categories: [document]
  - name: images
    label: Images
    input: images
    output: /images
    categories: [image]

content:
  - name: blog_posts
    label: Blog posts
    type: collection
    path: content
    format: yaml-frontmatter
    filename: "{slug}.md"
    view:
      fields: [title, publishDate, author, tags]
      primary: title
      sort: [publishDate, title]
      default:
        sort: publishDate
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        description: "Used for filenames and URLs. Lowercase letters, numbers, and hyphens only."
        required: true
        pattern:
          regex: "^[a-z0-9-]+$"
          message: "Use lowercase letters, numbers, and hyphens."
      - name: publishDate
        label: Publish date
        type: date
        required: true
      - name: author
        label: Author
        type: string
        default: "Digital Allies"
      - name: description
        label: Meta description
        type: text
        options:
          maxlength: 160
      - name: category
        label: Category
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: featuredImage
        label: Featured image
        type: image
        options:
          media: images
      - name: featuredImageAlt
        label: Featured image alt text
        type: string
      - name: body
        label: Body
        type: rich-text
        options:
          media: images
