siteName: Digital Allies
siteDescription: Creating digital solutions for the real world.
logo: /assets/logo/digital-allies-logo-default.svg
security:
  enableUserRegistration: false
  requireEmailVerification: false
  maintenanceMode: false
features:
  enableBlog: true
  enableShop: false
  enableComments: false
contactEmail: contact@digitalallies.net
