siteName: Digital Allies
siteDescription: Creating digital solutions for the real world.
logo: /assets/logo/digital-allies-logo-default.svg
security:
  enableUserRegistration: true
  requireEmailVerification: true
  maintenanceMode: false
features:
  enableBlog: true
  enableShop: false
  enableComments: true
contactEmail: contact@digitalallies.net
